name: pbl6mobile
description: "pbl6"
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.9.0-333.2.beta

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  page_transition: ^2.2.1
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  http: ^1.5.0
  flutter_secure_storage: ^9.2.4
  flutter_dotenv: ^6.0.0
  logger: ^2.6.1
  retry: ^3.1.2
  html_editor_enhanced: ^2.7.1
  flutter_html: ^3.0.0
  timezone: ^0.10.1
  dropdown_button2: ^2.3.9
  sqflite: ^2.4.2
  connectivity_plus: ^7.0.0
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  flutter_animate: ^4.5.2
  flutter_slidable: ^4.0.3
  flutter_quill: ^11.4.1
  flutter_quill_extensions: ^11.0.0
  vsc_quill_delta_to_html: ^1.0.5
  dio: ^5.9.0
  dio_smart_retry: ^7.0.1
  cached_network_image: ^3.4.1
  image_picker: ^1.2.0
  flutter_svg: ^2.2.1
  flutter_launcher_icons: ^0.14.4
  syncfusion_flutter_calendar: ^31.1.19
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.7.0
  freezed: ^3.2.0
  json_serializable: ^6.10.0
  test: ^1.24.0
  flutter_localization: ^0.3.3


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_app.png"
  min_sdk_android: 21
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/
    - .env
    - assets/data/login_test_data.json

